### ISSUE TITLE
Suggested Feature

### ISSUE THREAD

**Issue by TalkinBout** [dav-apps/UniversalSoundboard#10]
Not an issue, but was hoping to suggest a feature.  Just wondering if it was possible to have a toggle for "fade out sound on stop" to the settings.  If off things will work as they do now, if on however when you click to stop the sound playing part way through the sound it would fade out over a few seconds rather than just stopping.

Thanks!

**Comment by Dav2070** [comment]
Thanks for the suggestion! There already is a fade out effect, but maybe it's too subtle (it's like 200 ms or something). I will keep this in mind for the future, but can't promise anything.

**Comment by Langenfeld** [comment]
Extending on this request: it would be nice to have a customisable global fade-in and fade-out configuration. 

As I use UniversalSoundboard for rpg ambient, a gentle fade in of tracks (e.g. 2 seconds) would stop individual tracks from noticably appearing or disappearing. This fade configuration might be undesriable if the board is configured with short shounds only.

**Comment by Dav2070** [comment]
This suggestion in now finally implemented in v2.4.
Read more about it here: https://blog.dav-apps.tech/universalsoundboard-2-4/
