### ISSUE TITLE
Can you make a mic for Universal Sound board?

### ISSUE THREAD

**Issue by Lieoneil** [dav-apps/UniversalSoundboard#11]
Can you make a mic for Universal Sound board if i use my mic it dosent work

**Comment by Dav2070** [comment]
Thank you for the suggestion! Creating sounds from the microphone is one feature I want to add in a future update, but it will take some time.

**Comment by Dav2070** [comment]
Hey, you can now use your microphone to create sounds! See [blog.dav-apps.tech/universalsoundboard-2-3](https://blog.dav-apps.tech/universalsoundboard-2-3/)
