### ISSUE TITLE
Multiple Output Devices

### ISSUE THREAD

**Issue by Bopler** [dav-apps/UniversalSoundboard#12]
Hi, it would be useful to have two output devices. This is so that you can have one output set to your virtual audio cable, and another set to your speakers so you can hear what sound is being played.

**Comment by Dav2070** [comment]
Hi, thanks for the suggestion, I didn't know about virtual audio cables. I will keep this issue open and see what I can do in this regard when I work on the next update.

**Comment by Dav2070** [comment]
Hey there, with v2.5 you can now set multiple output devices ✌️
[blog.dav-apps.tech/universalsoundboard-2-5](https://blog.dav-apps.tech/universalsoundboard-2-5/)
