### ISSUE TITLE
Delay on Win 10

### ISSUE THREAD

**Issue by digitechnc** [dav-apps/UniversalSoundboard#13]
When I press a button for a sound there is a 9 second delay before the sound plays on windows 10.  This just happened within the past 5 days.

**Comment by Dav2070** [comment]
Hey, thanks for the report! Does this always happen or only occasionally when playing a sound? Does it also happen after restarting the app?

**Comment by digitechnc** [comment]
It happens every time with every sound when clicking on a button. I have
restarted the app. I have restarted my laptop and every sound still plays
approximately 9 seconds after I press the button. I uninstalled and
reinstalled the app also. It still is delayed.  If I press the play button
up top that plays the entire list, that plays immediately.

**Comment by digitechnc** [comment]
Hey David, I started my laptop this morning and now it is working properly
again.  I have done nothing but it seems to be working again.

**Comment by Dav2070** [comment]
Okay, that's interesting. It seems to be some weird behaviour by Windows.
Feel free to reopen this issue if it happens again.

**Comment by digitechnc** [comment]
Hey David, it is now doing the same thing again. Same delay on all sounds
and now the app is crashing. I tried to send a video of what it is doing,
but it said the message was undeliverable because the file size was too
big.

**Comment by Dav2070** [comment]
The video would be very helpful, you can try to send it per email: support@dav-apps.tech or maybe upload it somewhere and share the link.
Additionally, could you share your version of Windows 10 and what device you have?

**Comment by Dav2070** [comment]
Thanks for the video! I found the corresponding crashes in my Analytics, so no need for the info. I will investigate this and let you know the results as soon as possible.

**Comment by digitechnc** [comment]
Thanks!  I use your app during my radio show broadcast and it's very
important for it to work properly.

**Comment by Dav2070** [comment]
By the way, this seems to be an issue with the layout in the list of the playing sounds. You can try using the single sound mode (in the settings: "Allow multiple opened sounds" turned off), where there is only one opened sound on the bottom of the app.

**Comment by Dav2070** [comment]
Or turn off "Show opened sounds" and see if this works.

**Comment by digitechnc** [comment]
I will try that during my broadcast tonight!  Thanks for your help!

**Comment by Dav2070** [comment]
Sorry for the delay, but Version 2.2.8 is now available in the Microsoft Store. Please let me know if this fixes the issue.

**Comment by digitechnc** [comment]
My laptop is at home. I will download and test tonight and let you know.
Thanks!
