### ISSUE TITLE
Downloaded (auto-generated?) YouTube songs won't play 

### ISSUE THREAD

**Issue by ShrimpCryptid** [dav-apps/UniversalSoundboard#14]
I've been encountering a possible issue where, when songs are downloaded from YouTube, some songs play properly and others don't. When I click on one of the bugged songs, they appear and instantly disappear from the right-side panel, with the progress bar instantly completing. The duration appears to be correct when it briefly appears, and when I look at the properties everything appears to be in order.

![image](https://user-images.githubusercontent.com/30200665/195758843-8756f67c-28da-456c-bbb0-678404bb1725.png)

Example properties:
![image](https://user-images.githubusercontent.com/30200665/195758741-47cfdb85-c2eb-44e5-8166-f530c5dbc7a0.png)

It seems like the songs that are misbehaving are auto-generated YouTube videos of soundtracks with static images? If I download it from alternative, user-uploaded videos there don't seem to be any issues.

I've compiled a short list of songs that are and are not downloading correctly, with alternative links that do. All of the bugged songs appear to be auto-generated by YouTube. 

Songs that are misbehaving:
- `Lost but Warm` by `Amos Roddy & ToyTree - Topic` (auto-generated, https://www.youtube.com/watch?v=7ctX8OIjkM0)
- ` Hide and Seek` by `ALEXEY NECHAEV` (auto-generated, https://www.youtube.com/watch?v=MrtA5QRRI48)
- `Driftwood` by `Amos Roddy & ToyTree - Topic` (auto-generated, https://www.youtube.com/watch?v=mEv144vvFRU)
- `Derelicts` by `Keith Power - Topic` (auto-generated, https://www.youtube.com/watch?v=DHC-Kaknc1I)

Songs that are working:
- `Kingdom: Two Crowns OST: Lost but Warm` by `Amos Roddy` (https://www.youtube.com/watch?v=YH69ERdcx60)
- `Hide and Seek` by `GameSND` (https://www.youtube.com/watch?v=hbPm5DyXB4o)
- `Kingdom: Two Crowns | Driftwood | HD` by `Soundtracks` (static image, https://www.youtube.com/watch?v=2PwiZtheyGo)
- `Warframe Soundtrack - Derelicts - Keither Power` by `StallordD` (static image, https://www.youtube.com/watch?v=gMFrb82d1zA)

UniversalSoundboard Version: 2.2.10
Windows Version: 10.0.22000 Build 22000

Please let me know if you need any additional information, and thank you for your time!

**Comment by Dav2070** [comment]
Hey, thank you for the bug report (and sorry for the late response). Your list is very helpful, and I can reproduce the issue on my machine. I will look into it and let you know when I find out more.

**Comment by Dav2070** [comment]
Okay, this is weird. The download works fine, but the audio file returned by the YouTube API is somehow broken. The preinstalled Windows media apps can't play the file, but the browser and some other apps can. As UniversalSoundboard uses Windows APIs for playing audio, I'm not sure what can be done about this.
I will keep this issue open and see if I can find a solution at a later time.

**Comment by ShrimpCryptid** [comment]
Glad that it's reproducible on your machine! Definitely a strange bug, thank you for looking into it.

**Comment by Dav2070** [comment]
This issue is finally fixed with v2.5.1 🎉
