### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by Gimi1967** [dav-apps/UniversalSoundboard#2]
First. I like the the app very much. It's simple and easy to use. But there are some things I would like to see if you consider it relevant and have time.
1. Change size of font on the buttons and, if possible, allow multiple lines of text. (list view like the Android layout would also work)
2. Drag and drop sounds into category.
3. Support for webp image format (Low priority, I can convert)
4. Smaller button size (small, medium, large) would be nice, where current size is large.

**Comment by Dav2070** [comment]
Thank you for the valuable feedback!

1. The list view is definitely on the list for the next major release
2. That's a good idea. I added that to the list.
3. I never used WebP before, but that's also added to the list
4. I think the button size is okay, at least for tablets and smaller devices, but for mouse input, that's true
