### ISSUE TITLE
App crashes when exporting whole data

### ISSUE THREAD

**Issue by Guts** [dav-apps/UniversalSoundboard#5]
L'application crash au moment d'exporter le SoundBoard (onglet Données). L'export semble bien se dérouler

J'ai essayé dans différents dossiers de destination mais ça plante à chaque fois. Où puis-je trouver le log?

Pour information, je ne suis pas parvenu à reproduire le bug avec un SoundBoard d'exemple (environ 5 sons seulement). Peut-être la prise en charge de caractères spéciaux (je suis sur un ordinateur en Français) ?

**Comment by Dav2070** [comment]
Merci pour l'information!

Sur mes ordinateurs l'application ne plante pas à l'exportation d'entière Soundboard, mais à exporter tous les fichiers (sur Tous les sons > Tout sélectionner > Exporter).

L'error est "Le processus ne peut pas accéder au dossier parce qu'il est utilisé par un autre processus." à copier les fichiers sons. Je suppose que c'est la même erreur que d'exporter tout le Soundboard.

Je vais corriger le bug dès que possible et publier une mise à jour!

**Comment by Dav2070** [comment]
J'ai publié la mise a jour (v1.7.11), peux-tu essayer l'export encore une fois?

**Comment by Guts** [comment]
(sorry, I forgot to translate my previous message).

So, thanks for the quick fix. Unfortunately, I tried again with the latest released version and it's still failing during export. I made a quick screencast allowing to see the crash in action:

![universal_soundboard_export_crash](https://user-images.githubusercontent.com/1596222/86570585-7184ea80-bf70-11ea-8667-8ff2ba03d4d5.gif)

Hope it helps!

**Comment by Dav2070** [comment]
Thank you, the video was very helpful!
I just uploaded another update, I hope that fixes it.

**Comment by Guts** [comment]
I tried with the last version and it's still crashing in the same way :/

**Comment by Dav2070** [comment]
Okay, thanks for trying it out. I will see if I can implement error handing or something to find out what exactly the error is.

**Comment by Dav2070** [comment]
I just released version 1.7.15. The issue itself is not fixed, but the app should not crash anymore and the exception should be sent to my server, so I can fix it later.

**Comment by Guts** [comment]
Ok. I'll give it a try.
