### ISSUE TITLE
Fading out for stopping sounds

### ISSUE THREAD

**Issue by Langenfeld** [dav-apps/UniversalSoundboard#7]
When pressing the "x" in the player, the sound stops right away. It would be nice to have a second button that fades the sound out over 1 to 2 seconds.

For some bachground, I use the board for ambient sounds in ttrpg, for example rain, or cave sounds or things like that (and UniversalSoundboard is finally a well working tool for that!), but stopping a track does lead to this unpleasant sudden transition.

**Comment by Dav2070** [comment]
Thanks for the suggestion! Your use case is very interesting; I will see if I can add this feature with the next update.
