### ISSUE TITLE
An option to set the playback device 

### ISSUE THREAD

**Issue by WerDei** [dav-apps/UniversalSoundboard#8]
Currently the app uses the Windows's default playback device, I'm assuming. The option to choose where to output the audio to would allow for better control.

**Comment by Dav2070** [comment]
Hi, thanks for the suggestion! I will see if I can add an option for changing the output device with the next update, but it will take some time.

**Comment by awise107** [comment]
+1 for this suggestion! that would be very useful.

**Comment by igromanru** [comment]
Quick tip for all Windows 10 users:  
Under "Sound settings" you can find in the bottom "Advanced sound options", there you can change Ouput and Input device for each single application.

**Comment by Dav2070** [comment]
Hey folks, thanks for your patience! With the latest update, you can now change the output device for the entire app.
With dav Plus, you can also change the output device for each sound individually, making it possible to play different sounds on different devices at the same time!

Learn more in my blog post: [https://blog.dav-apps.tech/universalsoundboard-2-1/](https://blog.dav-apps.tech/universalsoundboard-2-1/)
