### ISSUE TITLE
Env.Cs

### ISSUE THREAD

**Issue by babakmdi** [dav-apps/UniversalSoundboard#9]
i cant find this on project, should i create it?

**Comment by Dav2070** [comment]
Yes, you need to add it manually, it looks like this:
```
namespace UniversalSoundboard
{
    public class Env
    {
        public static string DavApiKeyDev = "";
        public static string DavApiKeyProd = "";
        public static string AppCenterSecretKey = "";
    }
}
```

**Comment by babakmdi** [comment]
thanks, what is the Davapikeydev , DavApiKeyProd ,AppCenterSecretKey  ? should this be null?

**Comment by Dav2070** [comment]
At least the AppCenterSecretKey is supposed to be secret (that's why it's not in the repo), so you can leave it empty.
The dav API keys are for the login functionality, you probably don't need these:
```
public static string DavApiKeyDev = "eUzs3PQZYweXvumcWvagRHjdUroGe5Mo7kN1inHm";
public static string DavApiKeyProd = "gHgHKRbIjdguCM4cv5481hdiF5hZGWZ4x12Ur-7v";
```
